Vagrant.configure("2") do |config|
    # Provider for Docker
    config.vm.provider :docker do |docker, override|
      override.vm.box = nil
      docker.image = "rudester/vagrant-docker-mysql:5.7-r0.4"
      docker.remains_running = true
      docker.has_ssh = true
      docker.privileged = true
      docker.volumes = ["/sys/fs/cgroup:/sys/fs/cgroup:ro"]
      docker.ports = ["3306:3306"]
      docker.create_args = ['--platform=linux/amd64']
    end
    config.vm.hostname = "vagrant-docker-mysql-box"
  end