Vagrant.configure("2") do |config|
    # Provider for Docker
    config.vm.provider :docker do |docker, override|
      override.vm.box = nil
      docker.image = "rudester/kubernetes-terraform-lab:v0.7.0"
      docker.remains_running = true
      docker.has_ssh = true
      docker.privileged = true
      docker.volumes = ["/sys/fs/cgroup:/sys/fs/cgroup:ro", "<HOST_DIR>:<GUEST_DIR>"]
      docker.create_args = ['--platform=linux/amd64']
    end
    config.vm.hostname = "kubernetes-terraform-lab"
    config.vm.network "private_network", ip: "10.0.0.20"
    config.vm.synced_folder "<HOST_DIR>", "<GUEST_DIR>"
    config.vm.provision :shell, path: "provisioner.sh"
  end