Vagrant.configure("2") do |config|
    # Provider for Docker
    config.vm.provider :docker do |docker, override|
      override.vm.box = nil
      docker.image = "rudester/vagrant-docker-nodejs:nvm-v0.39.1-r0.1"
      docker.remains_running = true
      docker.has_ssh = true
      docker.privileged = true
      docker.volumes = ["/sys/fs/cgroup:/sys/fs/cgroup:ro"]
      docker.create_args = ['--platform=linux/amd64']
    end
    config.vm.hostname = "vagrant-docker-nodejs-box"
    config.vm.network "private_network", ip: "10.0.0.13"
  end